apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-k8s
  namespace: argocd
  labels:
    app: nginx-k8s
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mohammad9227/repo-for-argocd.git'
    path: "app_deploy*"
    targetRevision: HEAD  # or specify a branch, tag, or commit
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true