apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
  labels:
    name: nginx-helm
spec:
  project: default
  source:
    repoURL: https://charts.helm.sh/stable  # Assuming using the stable repository.
    targetRevision: '*'  # Use '*' for latest or specify a version like '1.2.3'.
    chart: nginx
    helm:
      values: |  # Customize these values as needed.
        controller:
          replicaCount: 2
          service:
            type: LoadBalancer
        rbac:
          create: true
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false